In [1]:
import pandas as pd
import numpy as np

In [3]:
s = pd.Series([1,3,6,np.nan,44,1])

In [4]:
s

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64

In [5]:
dates = pd.date_range('20260923',periods=6)

In [6]:
dates

DatetimeIndex(['2026-09-23', '2026-09-24', '2026-09-25', '2026-09-26',
               '2026-09-27', '2026-09-28'],
              dtype='datetime64[us]', freq='D')

In [8]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=['a','b','c','d'])

In [9]:
df

                   a         b         c         d
2026-09-23  1.912138  0.324984 -1.729780 -0.906023
2026-09-24  0.897860  0.974505 -1.179440  2.476962
2026-09-25 -1.201287  1.233126  1.076433  1.544129
2026-09-26  0.378278 -1.124762  1.140622 -0.861257
2026-09-27  0.836452  1.530470 -0.188780 -0.861482
2026-09-28  1.341222 -1.079389 -0.123107  0.055221

In [18]:
df1=pd.DataFrame(np.arange(12).reshape((3,4)))    #()为元组，元素不可改；[]为列表，元素可改

In [17]:
df1

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [24]:
df2=pd.DataFrame({'A':1,
                  'B':pd.Timestamp('20130102'),
                  'C':pd.Series(1,index=list(range(4)),dtype='float32'), #{}为字典，需要key和值
                  'D':np.array([3]*4,dtype='int32'),
                  'E':pd.Categorical(["test","trian","test","trian"]),
                  'F':'foo'})

In [23]:
df2

   A          B    C  D      E    F
0  1 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  trian  foo
2  1 2013-01-02  1.0  3   test  foo
3  1 2013-01-02  1.0  3  trian  foo

In [25]:
df2.index

Index([0, 1, 2, 3], dtype='int64')

In [26]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')

In [27]:
df2.values

array([[1, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'trian', 'foo'],
       [1, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'trian', 'foo']],
      dtype=object)

In [29]:
df2.describe()

         A                    B    C    D
count  4.0                    4  4.0  4.0
mean   1.0  2013-01-02 00:00:00  1.0  3.0
min    1.0  2013-01-02 00:00:00  1.0  3.0
25%    1.0  2013-01-02 00:00:00  1.0  3.0
50%    1.0  2013-01-02 00:00:00  1.0  3.0
75%    1.0  2013-01-02 00:00:00  1.0  3.0
max    1.0  2013-01-02 00:00:00  1.0  3.0
std    0.0                  NaN  0.0  0.0

In [30]:
df2.T

,0,1,2,3
A,1,1,1,1
B,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00
C,1.0,1.0,1.0,1.0
D,3,3,3,3
E,test,trian,test,trian
F,foo,foo,foo,foo

In [31]:
df2.sort_index(axis=1,ascending=False)

     F      E  D    C          B  A
0  foo   test  3  1.0 2013-01-02  1
1  foo  trian  3  1.0 2013-01-02  1
2  foo   test  3  1.0 2013-01-02  1
3  foo  trian  3  1.0 2013-01-02  1

In [33]:
df2.sort_values(by='E')

   A          B    C  D      E    F
0  1 2013-01-02  1.0  3   test  foo
2  1 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  trian  foo
3  1 2013-01-02  1.0  3  trian  foo

In [38]:
#df['A'] == df.A
df2[0:3]

   A          B    C  D      E    F
0  1 2013-01-02  1.0  3   test  foo
1  1 2013-01-02  1.0  3  trian  foo
2  1 2013-01-02  1.0  3   test  foo

In [61]:
df2.loc[:,['A','B']] #loc[]用于筛选 ，混合筛选，和改动元素（赋值）
df2.iloc[3:5,1:3]   #iloc[]用于切割筛选或改动元素
                     #ix[]用于混合loc和iloc，混合筛选，但新版本已经删掉了，直接用loc[]即可
df2.loc[:3,['A','C']] #混合筛选

   A    C
0  1  1.0
1  1  1.0
2  1  1.0
3  1  1.0

In [62]:
#另外还可以用条件来筛选，和改动元素
df[df.a<0]

                   a         b         c         d
2026-09-25 -1.201287  1.233126  1.076433  1.544129

In [64]:
###############################处理丢失数据##################################

In [66]:
#df.dropna(axis=0/1,how='any'/'all')用于删除丢失值对应的行或列，how用来判断这行或列是出现nan就删还是全是nan才删

In [67]:
#df.fillna(value=xxx)用于填充nan的地方

In [70]:
#df.isnull()用来检查字典中有没有丢失数据，输出仍为一个列表，全由T，F构成
np.any(df.isnull())==True #直接返回字典中有没有nan

np.False_

In [71]:
##############################导入导出#####################################

In [75]:
#data=pd.read_csv('文件名.csv')用来导入文件
#data.to_csv('文件名.csv')用来导出文件